Add: org.opencontainers.image labels
jellyfin/jellyfin-packaging pull request #25
Opened 2024-05-18 12:10 UTC by JB26

Fixes Issue #24

2024-05-18 13:02 UTC, ferferga requested changes
Since long ago, labels were squashed into a single layer, so the benefit of keeping them in a single instruction does not exist as far as I know and they decrease legibility.

See https://docs.docker.com/reference/dockerfile/#label

Is there any other reason I'm missing?

2024-05-19 10:44 UTC, JB26 commented
> Is there any other reason I'm missing?

Nope, just wasn't aware of it. I changed it to multiple label instructions

2024-05-19 11:39 UTC, ferferga approved these changes

2024-05-19 13:59 UTC, crobibero approved these changes

2024-05-19 13:59 UTC, merged